# Generated by Django 5.0.7 on 2025-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0002_remove_user_activation_uuid_remove_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
