# Generated by Django 5.2.1 on 2025-05-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0003_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default='Test', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
