# Generated by Django 5.2.1 on 2025-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0004_alter_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='booths',
            field=models.ManyToManyField(blank=True, to='BookABooth_Django.booth'),
        ),
    ]
