# Generated by Django 5.2.1 on 2025-05-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0005_servicepackage_booths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='booths',
        ),
    ]
