# Generated by Django 5.2.1 on 2025-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0006_remove_servicepackage_booths'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
