# Generated by Django 5.2.1 on 2025-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0007_termsupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
