# Generated by Django 5.2.1 on 2025-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0008_company_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
