# Generated by Django 5.2.1 on 2025-06-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_reimbursement', models.PositiveIntegerField(default=100)),
                ('cancellation_reimbursement_until', models.DateField()),
            ],
        ),
    ]
