# Generated by Django 5.2.1 on 2025-06-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0010_systemconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='BookABooth_Django.company'),
        ),
    ]
