# Generated by Django 5.2.1 on 2025-06-17 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0011_alter_booking_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='BookABooth_Django.booth'),
        ),
    ]
