# Generated by Django 5.2.1 on 2025-06-26 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookABooth_Django', '0012_alter_booking_booth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booth_bookings', to='BookABooth_Django.booth'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_bookings', to='BookABooth_Django.company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='blocked', max_length=20),
        ),
        migrations.AlterField(
            model_name='booth',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='BookABooth_Django.location'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='service_package',
            field=models.ManyToManyField(blank=True, related_name='booths', to='BookABooth_Django.servicepackage'),
        ),
        migrations.AlterField(
            model_name='location',
            name='site_plan',
            field=models.ImageField(upload_to='site_plan/'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=21),
        ),
    ]
